---
title: "Kmeans_ARDS_phenotypes_Noncovid"
output: html_document
date: "2025-06-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r, echo=FALSE, results='hide'}
library(FactoMineR)
library(factoextra)
library(dplyr)
library(ggplot2)
library(Hmisc)
library(mice, warn.conflicts = FALSE)
library(VIM)
library(RColorBrewer)
library(viridis)
library(hrbrthemes)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(naniar)
library(reshape2)

CDdataset <- read_excel("C:/Users/cononye/Desktop/RStudio/Amylase/CDdataset.xlsx")
EDW_bal_results <- read_excel("C:/Users/cononye/Desktop/RStudio/Amylase/EDW_bal_results.xlsx")
Basic_endpoints052825 <- read_excel("C:/Users/cononye/Desktop/RStudio/Amylase/Basic_endpoints052825.xlsx")

## Get non-covid samples from SCRIPT dataset, use first BAL from each patient
kmeans_df <- CDdataset[grep("BAL-00", CDdataset$bal_barcode), ]

## Add a column for Mortality
kmeans_df <- kmeans_df %>% mutate(Mortality = case_when(discharge_disposition_name == 'Died' ~ "1"))
kmeans_df <- kmeans_df %>% mutate(Mortality = ifelse(is.na(Mortality), 0, Mortality))

## Remove duplicate patient IRIDs
Merged_df = merge(kmeans_df, EDW_bal_results, by.x=c("patient_ir_id", "bal_dt"), by.y=c("patient_ir_id", "bal_collection_date"))
df <- Merged_df[!duplicated(Merged_df$patient_ir_id),]

## Remove Covid patients
df_noncovid <- subset(df, covid_status_enrollment == "FALSE")
df_noncovid <- subset(df_noncovid, episode_category != "NPC")

```

## Create dataframe of ARDS phenotype variables

```{r, include=FALSE}
#Select datapoints that were checked in ARDS phenotypes
datapoints <- df_noncovid %>% select(heart_rate_avg, minute_ventilation_avg, mean_arterial_pressure_avg, plateau_pressure_avg, creatinine_avg, respiratory_rate_avg, peep_avg, bilirubin_avg, temperature_avg, hemoglobin_avg, wbc_avg, bmi, edw_adm_age, po2_fio2_ratio_avg, albumin_avg, platelet_avg, systolic_blood_pressure_avg, bicarbonate_avg, gender, sodium_avg, glucose_avg, cumulative_intubation_days, amylase, hospital_los_days, total_icu_los_days, Mortality, bal_barcode, episode_category, pathogen_bacteria, pathogen_virus, patient_ir_id, pt_study_id, bal_pct_neutro, bal_pct_lympho)

#Ensure all variables are numeric
datapoints$gender[datapoints$gender == "Female"] <- 2
datapoints$gender[datapoints$gender == "Male"] <- 1
datapoints$gender <- as.numeric(datapoints$gender)

datapoints$heart_rate_avg <- as.numeric(datapoints$heart_rate_avg)
datapoints$respiratory_rate_avg <- as.numeric(datapoints$respiratory_rate_avg)
datapoints$temperature_avg <- as.numeric(datapoints$temperature_avg)
datapoints$po2_fio2_ratio_avg <- as.numeric(datapoints$po2_fio2_ratio_avg)
datapoints$systolic_blood_pressure_avg <- as.numeric(datapoints$systolic_blood_pressure_avg)
```

## Impute and Scale Missing Data

```{r, echo=FALSE, results='hide', include=FALSE}

imp_datapoints <- mice(datapoints,m=5,maxit=50,meth='cart',seed=500)
datapoints_complete <- complete(imp_datapoints,1)

data_scaled <- datapoints_complete %>% mutate_at(c('heart_rate_avg', 'minute_ventilation_avg', 'mean_arterial_pressure_avg', 'plateau_pressure_avg', 'creatinine_avg', 'respiratory_rate_avg', 'peep_avg', 'bilirubin_avg', 'temperature_avg', 'hemoglobin_avg', 'wbc_avg', 'bmi', 'edw_adm_age', 'po2_fio2_ratio_avg', 'albumin_avg', 'platelet_avg', 'sodium_avg', 'systolic_blood_pressure_avg', 'gender', 'bicarbonate_avg', 'glucose_avg'), ~(scale(.) %>% as.vector))

distance <- get_dist(data_scaled[1:21])
fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))

```

## Find Optimal Number of Clusters 

```{r}

fviz_nbclust(data_scaled[1:21], kmeans, method = "silhouette")
 
#Create Kmeans clusters
k2 <- kmeans(data_scaled[1:21], centers = 2, nstart = 25)
fviz_cluster(k2, data = data_scaled[1:21], geom="point", ellipse = TRUE, ellipse.type = "norm", ellipse.level = 0.95, ellipse.alpha = 0.2, pointsize = 4, palette="Set1", ggtheme=theme_minimal())

#Summarize data
Summary_data <- data_scaled[1:21] %>% mutate(Cluster = k2$cluster) %>% group_by(Cluster) %>%  summarise_all("mean")

#Extract patient-level descriptive data, by adding a column that assigns a Cluster to the patient from the Kmeans data
data_scaled_clusters <- data_scaled %>% mutate(Cluster = k2$cluster) 

```

## Create Linegraph of Pneumonia Clusters

```{r}

linegraph_df <- data_scaled_clusters %>% select(plateau_pressure_avg, respiratory_rate_avg, peep_avg, minute_ventilation_avg,  bmi, heart_rate_avg, gender, glucose_avg, wbc_avg, creatinine_avg, platelet_avg, bilirubin_avg,  temperature_avg, albumin_avg, mean_arterial_pressure_avg, systolic_blood_pressure_avg, hemoglobin_avg, sodium_avg, bicarbonate_avg, edw_adm_age, po2_fio2_ratio_avg, Cluster)
df.m <- melt(linegraph_df, id.var = "Cluster")
df.m$value <- as.numeric(df.m$value)
sum_d <- df.m %>% group_by(Cluster, variable) %>% summarise(hp_mean = mean(value))
sum_d$Cluster <- as.factor(sum_d$Cluster)

p <- sum_d %>% ggplot(aes(x = variable, y = hp_mean, group = Cluster)) + geom_line(aes(color = Cluster), linewidth=1.5)
p + theme_bw() + scale_color_brewer(palette = "Set1") + ggtitle("Non Covid Pneumonia Clusters by ARDS Phenotype Variables") + theme(plot.title = element_text(hjust=0.5)) + theme(legend.text = element_text(size=14), axis.title=element_text(size=14), legend.title = element_text(size=14)) + labs(y="Scaled Mean", x="") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=12)) + scale_x_discrete(labels=c("plateau_pressure_avg" = "Plateau Pressure", "respiratory_rate_avg" = "Respiratory Rate", "peep_avg" = "PEEP", "minute_ventilation_avg"="Minute Ventilation", "bmi"="BMI", "gender"="Gender", "wbc_avg"="WBC",  "heart_rate_avg"="Heart Rate", "platelet_avg"="Platelets", "creatinine_avg"="Creatinine", "bilirubin_avg"="Bilirubin", "albumin_avg"="Albumin", "hemoglobin_avg"="Hemoglobin",  "temperature_avg"="Temperature", "amylase"="BAL Fluid Amylase", "bicarbonate_avg"="Bicarbonate", "sodium_avg"="Sodium",  "systolic_blood_pressure_avg"="Systolic Blood Pressure", "mean_arterial_pressure_avg"="MAP",  "edw_adm_age"="Age", "po2_fio2_ratio_avg"="P:F Ratio", "glucose_avg"="Glucose"))

```

## Find Outcomes by Cluster

```{r}
#Outcomes by Cluster

list_of_labels <- list(amylase="BAL Fluid Amylase Level, U/L", bal_pct_neutro="BAL Neutrophil Percentage", pathogen_bacteria="Bacteria Detected", pathogen_virus="Virus Detected", cumulative_intubation_days="Cumulative Intubation Days", episode_category="Pneumonia Episode Category", hospital_los_days="Hospital Length of Stay, days", total_icu_los_days="Total ICU Length of Stay, days", Mortality="Hospital Discharge Status, n (%)")

data_scaled_clusters %>% select(Cluster, amylase, episode_category, bal_pct_neutro, pathogen_bacteria, pathogen_virus, cumulative_intubation_days, hospital_los_days, total_icu_los_days, Mortality) %>% tbl_summary(by= Cluster, statistic = list(all_continuous() ~ "{median} ({p25}, {p75})", all_categorical() ~ "{n} ({p}%)"), label=list_of_labels, ) %>% add_p(pvalue_fun = label_style_pvalue(digits = 2))

```


